<?php

/**
 * Let op: oauth2_server heeft geen API om automatisch servers of clients toe te voegen.
 * Dat betekent dat via Structuur -> OAuth2 Servers een server moet worden aangemaakt met de volgende instellingen:
 * - Naam: Main. 'Require exact redirect uri' uitvinken.
 * - Scope toevoegen met systeemnaam 'sp'.
 * - Clients toevoegen voor iedere site. Vul de exacte redirect-uri in (voor Drupal-sites: https://<sitenaam>/oauth/authorized2/1) en vink het hokje 'Automatically authorize this client' aan.
 * De onderstaande hooks zorgen voor het beschikbaar maken van een API om informatie over de ingelogde gebruiker en zijn groepen op te vragen.
 */

/**
 * Implementation of hook_default_services_endpoint().
 * Maakt een OAuth2-geauthenticeerde API beschikbaar onder /oauth2/api
 * @return array Endpoints
 */
function oauthloginprovider_default_services_endpoint() {
	$endpoint = new stdClass();
	$endpoint->disabled = false;
	$endpoint->api_version = 3;
	$endpoint->name = 'oauth2login';
	$endpoint->server = 'rest_server';
	$endpoint->path = 'oauth2/api';
	$endpoint->authentication = array(
		'oauth2_server' => array(
			'server' => 'main',
		),
	);
	$endpoint->server_settings = array(
		'formatters' => array(
			'bencode' => true,
			'json'    => true,
			'php'     => true,
			'xml'     => true,
			'jsonp'   => false,
		),
		'parsers'    => array(
			'application/json'                  => true,
			'application/vnd.php.serialized'    => true,
			'application/x-www-form-urlencoded' => true,
			'application/xml'                   => true,
			'multipart/form-data'               => true,
			'text/xml'                          => true,
		),
	);
	$endpoint->resources = array(
		'me' => array(
			'operations' => array(
				'index' => array(
					'enabled'  => '1',
					'settings' => array(
						'oauth2_server' => array(
							'require_authentication' => '1',
							'scope'                  => 'sp',
						),
					),
				),
			),
		),
		'roles' => array(
			'operations' => array(
				'index' => array(
					'enabled'  => '1',
					'settings' => array(
						'oauth2_server' => array(
							'require_authentication' => '0',
							'scope'                  => 'sp',
						),
					),
				),
			),
		),
	);
	$endpoint->debug = 1;

	$endpoints[$endpoint->name] = $endpoint;
	return $endpoints;
}


/**
 * Implementation of hook_services_resources().
 * API-method om informatie over een gebruiker op te halen vanaf een client-site.
 * @return array Resources
 */
function spoauthprovider_services_resources() {
	$res = array(
		'me' => array(
			'operations' => array(
				'index' => array(
					'access callback'         => 'user_access',
					'access arguments'        => array('use oauth2 server'),
					'help'                    => 'Retrieves information about the current user',
					'callback'                => 'spoauthprovider_me_index_action',
				),
			),
		),
		'roles' => array(
			'operations' => array(
				'index' => array(
					'access callback'         => 'user_access',
					'access arguments'	  => array('use oauth2 server'),
					'help'                    => 'Lists roles that are available on this Drupal installation',
					'callback'                => 'spoauthprovider_roles_index_action',
				),
			),
		),
	);
	return $res;
}

/**
 * API-actie onder /oauth2/api/me. Retourneert een object met de ingelogde user,
 * en een uitgebreid overzicht (met id's en namen) van (Drupal-)rollen.
 * @return object
 */
function spoauthprovider_me_index_action() {

	// Load entire user object (anders zijn extra velden niet beschikbaar)
	global $user;
	$myuser = user_load($user->uid);

	$data = (array)$myuser;
	$unset = array('pass', 'session', 'cache', 'sid', 'ssid', 'uuid', 'data', 'rdf_mapping');
	foreach($unset as $u) {
		if(array_key_exists($u, $data))
			unset($data[$u]);
	}

	foreach($data['roles'] as $key => &$value) {
		$data['roles'][$key] = array(
			'id' => $key,
			'name' => $value,
		);
	}

	foreach($data as $key => &$value) {
		if(is_array($value) && array_key_exists(LANGUAGE_NONE, $value))
			$value = $value[LANGUAGE_NONE][0]['value'];
	}

	return (object)$data;
}

/**
 * API-actie onder /oauth2/api/roles. Retourneert alle rollen die bestaan op deze installatie.
 * @return object
 */
function spoauthprovider_roles_index_action() {

	$data = array();

	foreach(user_roles(true) as $key => $name) {
		$data['roles'][$key] = array(
			'id' => $key,
			'name' => $name,
		);
	}

	return (object)$data;
}
